"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ChevronLeft, ChevronRight, Eye, Loader2, Pencil, Plus, Search, UserRoundX, Users, X } from "lucide-react";
import Sidebar from "../../components/Sidebar";
import ImportarEmpleadosExcel from "../../components/ImportarEmpleadosExcel";
import { obtenerEmpresasOperativasDesdeIds } from "../../lib/empresasOperativas";
import { esAuditorSoloLecturaLocal, listarFuncionesOperativasUsuario, tieneFuncionOperativaLocal, type UsuarioFuncionOperativa } from "../../lib/funcionesOperativas";
import { obtenerEmpresasPermitidas } from "../../lib/permisosEmpresas";
import { supabase } from "../../lib/supabase";
import { validarAccesoModuloUsuario } from "../../lib/validarAccesoModuloUsuario";

const PAGE = 25;
const ESTADOS = ["Activo", "Inactivo", "Suspendido", "Egresado"];
const COLS = "id,empresa_id,codigo_empleado,nombres,apellidos,dpi,nit,igss_numero,fecha_ingreso,fecha_egreso,puesto,departamento,tipo_contrato,jornada,salario_base,bonificacion_incentivo,moneda,activo,estado,observaciones,version,actualizado_at";
interface Empresa { id:number; nombre:string }
interface Perfil { rol:string }
interface Empleado { id:string; empresa_id:number; codigo_empleado:string|null; nombres:string; apellidos:string; dpi:string|null; nit:string|null; igss_numero:string|null; fecha_ingreso:string; fecha_egreso:string|null; puesto:string|null; departamento:string|null; tipo_contrato:string|null; jornada:string|null; salario_base:number; bonificacion_incentivo:number; moneda:string; activo:boolean; estado:string; observaciones:string|null; version:number; actualizado_at:string|null }
type Form = { empresaId:string; codigo:string; nombres:string; apellidos:string; dpi:string; nit:string; igss:string; ingreso:string; retiro:string; puesto:string; departamento:string; contrato:string; jornada:string; salario:string; bonificacion:string; moneda:string; estado:string; observaciones:string };
const vacio = (empresaId=""):Form => ({empresaId,codigo:"",nombres:"",apellidos:"",dpi:"",nit:"",igss:"",ingreso:"",retiro:"",puesto:"",departamento:"",contrato:"",jornada:"",salario:"0",bonificacion:"0",moneda:"GTQ",estado:"Activo",observaciones:""});
const desde = (e:Empleado):Form => ({empresaId:String(e.empresa_id),codigo:e.codigo_empleado||"",nombres:e.nombres,apellidos:e.apellidos,dpi:e.dpi||"",nit:e.nit||"",igss:e.igss_numero||"",ingreso:e.fecha_ingreso,retiro:e.fecha_egreso||"",puesto:e.puesto||"",departamento:e.departamento||"",contrato:e.tipo_contrato||"",jornada:e.jornada||"",salario:String(e.salario_base),bonificacion:String(e.bonificacion_incentivo),moneda:e.moneda,estado:e.estado,observaciones:e.observaciones||""});
const mask=(v?:string|null)=>!v?"No registrado":v.length<=4?"••••":`••••••${v.slice(-4)}`;
const opt=(v:string)=>v.trim()||null;

export default function EmpleadosPage(){
 const router=useRouter(); const [perfil,setPerfil]=useState<Perfil|null>(null); const [uid,setUid]=useState<string|null>(null); const [empresas,setEmpresas]=useState<Empresa[]>([]); const [ids,setIds]=useState<number[]>([]); const [funciones,setFunciones]=useState<UsuarioFuncionOperativa[]>([]);
 const [empleados,setEmpleados]=useState<Empleado[]>([]); const [empresa,setEmpresa]=useState(""); const [estado,setEstado]=useState(""); const [buscar,setBuscar]=useState(""); const [texto,setTexto]=useState(""); const [pagina,setPagina]=useState(1); const [total,setTotal]=useState(0);
 const [cargando,setCargando]=useState(true); const [guardando,setGuardando]=useState(false); const [error,setError]=useState<string|null>(null); const [mensaje,setMensaje]=useState<string|null>(null); const [modal,setModal]=useState<"ver"|"editar"|"crear"|null>(null); const [actual,setActual]=useState<Empleado|null>(null); const [form,setForm]=useState<Form>(vacio());
 useEffect(()=>{let ok=true;(async()=>{try{const a=await validarAccesoModuloUsuario("planilla");if(!a.ok){router.replace(a.motivo?.startsWith("sin_")?"/login":"/dashboard");return}const p=a.perfil as Perfil;const permitidas=await obtenerEmpresasPermitidas(a.user!.id,p.rol);const op=await obtenerEmpresasOperativasDesdeIds(permitidas);const fun=await listarFuncionesOperativasUsuario(a.user!.id,op.ids);if(ok){setPerfil(p);setUid(a.user!.id);setEmpresas(op.empresas);setIds(op.ids);if(op.ids.length===1)setEmpresa(String(op.ids[0]));setFunciones(fun)}}catch{if(ok)setError("No se pudo preparar el Maestro de Empleados.")}finally{if(ok)setCargando(false)}})();return()=>{ok=false}},[router]);
 const puede=(id:number|string)=>!!uid&&!esAuditorSoloLecturaLocal(funciones,[id])&&(["admin","jefe","supervisor"].includes((perfil?.rol||"").toLowerCase())||tieneFuncionOperativaLocal(funciones,uid,id,["auxiliar_contable","contador_revisor"]));
 const cargar=useCallback(async()=>{if(cargando||!ids.length)return;setCargando(true);setError(null);try{let q=supabase.from("empleados_planilla").select(COLS,{count:"exact"}).in("empresa_id",ids).order("apellidos").range((pagina-1)*PAGE,pagina*PAGE-1);if(empresa)q=q.eq("empresa_id",Number(empresa));if(estado)q=q.eq("estado",estado);const t=texto.trim().replace(/[,%()"']/g," ");if(t)q=q.or(`nombres.ilike.%${t}%,apellidos.ilike.%${t}%,codigo_empleado.ilike.%${t}%,puesto.ilike.%${t}%`);const {data,error:e,count}=await q;if(e)throw e;setEmpleados((data||[]) as Empleado[]);setTotal(count||0)}catch{setError("No se pudo cargar el listado de empleados.")}finally{setCargando(false)}},[cargando,ids,pagina,empresa,estado,texto]);
 useEffect(()=>{if(!cargando&&ids.length)void cargar()},[empresa,estado,texto,pagina,ids.length]);
 const nombres=useMemo(()=>new Map(empresas.map(e=>[e.id,e.nombre])),[empresas]); const paginas=Math.max(1,Math.ceil(total/PAGE));
 function abrir(e?:Empleado,modo:"ver"|"editar"|"crear"="crear"){setActual(e||null);setForm(e?desde(e):vacio(empresa||String(ids[0]||"")));setModal(modo);setError(null);setMensaje(null)}
 async function guardar(){if(guardando||!uid)return;setError(null);try{const eid=Number(form.empresaId);if(!ids.includes(eid)||!puede(eid))throw new Error("No tienes permiso para esta empresa.");if(!form.nombres.trim()||!form.apellidos.trim()||!form.ingreso)throw new Error("Empresa, nombres, apellidos y fecha de ingreso son obligatorios.");if(form.retiro&&form.retiro<form.ingreso)throw new Error("La fecha de retiro no puede ser anterior al ingreso.");if(Number(form.salario)<0||Number(form.bonificacion)<0)throw new Error("Los montos no pueden ser negativos.");setGuardando(true);const payload={empresa_id:eid,codigo_empleado:opt(form.codigo),nombres:form.nombres.trim(),apellidos:form.apellidos.trim(),dpi:opt(form.dpi),nit:opt(form.nit),igss_numero:opt(form.igss),fecha_ingreso:form.ingreso,fecha_egreso:form.retiro||null,puesto:opt(form.puesto),departamento:opt(form.departamento),tipo_contrato:opt(form.contrato),jornada:opt(form.jornada),salario_base:Number(form.salario||0),bonificacion_incentivo:Number(form.bonificacion||0),moneda:form.moneda,estado:form.estado,activo:form.estado==="Activo",observaciones:opt(form.observaciones)};const key=crypto.randomUUID();const {data,error:e}=await supabase.rpc(actual?"actualizar_empleado_v2":"crear_empleado_v2",actual?{p_empleado_id:actual.id,p_version_esperada:actual.version,p_datos:payload,p_idempotency_key:key}:{p_datos:payload,p_idempotency_key:key});if(e)throw new Error("La operación segura requiere aplicar la migración V2 en Supabase.");const r=data as {ok?:boolean;mensaje?:string};if(!r?.ok)throw new Error(r?.mensaje||"La operación fue rechazada.");setModal(null);setMensaje(r.mensaje||"Empleado guardado correctamente.");await cargar()}catch(e){setError(e instanceof Error?e.message:"No se pudo guardar.")}finally{setGuardando(false)}}
 if(cargando&&!uid)return <div className="flex min-h-screen items-center justify-center bg-[var(--background)] text-[var(--foreground)]"><Loader2 className="mr-2 animate-spin"/>Cargando…</div>;
 return <div className="empleados-maestro flex min-h-screen bg-[var(--background)] text-[var(--foreground)]"><Sidebar/><main className="min-w-0 flex-1 p-5 md:p-8"><div className="mx-auto max-w-7xl space-y-6">
  <header className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-3"><Users className="text-cyan-500" size={38}/><div><h1 className="text-3xl font-black">Maestro de Empleados</h1><p className="text-sm text-[var(--muted)]">Base laboral segura y separada de usuarios.</p></div></div><div className="flex flex-wrap gap-3"><ImportarEmpleadosExcel empresas={empresas} habilitado={ids.some(puede)} onImportado={cargar}/>{ids.some(puede)&&<button className="btn-primary inline-flex items-center gap-2" onClick={()=>abrir()}><Plus size={18}/> Nuevo empleado</button>}</div></header>
  <section className="grid gap-3 rounded-2xl border border-[var(--card-border)] bg-[var(--card)] p-4 md:grid-cols-4"><select className="input-custom" value={empresa} onChange={e=>{setEmpresa(e.target.value);setPagina(1)}}><option value="">Todas las empresas</option>{empresas.map(e=><option key={e.id} value={e.id}>{e.nombre}</option>)}</select><select className="input-custom" value={estado} onChange={e=>{setEstado(e.target.value);setPagina(1)}}><option value="">Todos los estados</option>{ESTADOS.map(e=><option key={e}>{e}</option>)}</select><form className="relative md:col-span-2" onSubmit={e=>{e.preventDefault();setTexto(buscar);setPagina(1)}}><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--muted)]" size={17}/><input className="input-custom w-full pl-10" value={buscar} onChange={e=>setBuscar(e.target.value)} placeholder="Nombre, código o puesto"/></form></section>
  {error&&<Aviso error>{error}</Aviso>}{mensaje&&<Aviso>{mensaje}</Aviso>}
  <section className="overflow-hidden rounded-2xl border border-[var(--card-border)] bg-[var(--card)]">{cargando?<div className="p-16 text-center"><Loader2 className="mx-auto animate-spin"/></div>:empleados.length?<div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr>{["Código","Empleado","Empresa","Puesto","Estado","Ingreso","Salario","Acciones"].map(h=><th key={h} className="p-4 text-left">{h}</th>)}</tr></thead><tbody>{empleados.map(e=><tr key={e.id} className="border-t border-[var(--card-border)]"><td className="p-4">{e.codigo_empleado||"—"}</td><td className="p-4"><b>{e.nombres} {e.apellidos}</b><p className="text-xs text-[var(--muted)]">DPI {mask(e.dpi)}</p></td><td className="p-4">{nombres.get(e.empresa_id)}</td><td className="p-4">{e.puesto||"—"}</td><td className="p-4">{e.estado}</td><td className="p-4">{e.fecha_ingreso}</td><td className="p-4">{["admin","jefe","contador"].includes((perfil?.rol||"").toLowerCase())?`${e.moneda} ${Number(e.salario_base).toFixed(2)}`:"Restringido"}</td><td className="p-4"><div className="flex gap-2"><button title="Ver" onClick={()=>abrir(e,"ver")}><Eye size={17}/></button>{puede(e.empresa_id)&&<><button title="Editar" onClick={()=>abrir(e,"editar")}><Pencil size={17}/></button><button title="Inactivar" onClick={()=>{if(window.confirm("¿Inactivar sin eliminar el empleado?")){abrir(e,"editar");setForm({...desde(e),estado:"Inactivo"})}}}><UserRoundX size={17}/></button></>}</div></td></tr>)}</tbody></table></div>:<div className="p-16 text-center text-[var(--muted)]">No hay empleados para estos filtros.</div>}<footer className="flex justify-between border-t border-[var(--card-border)] p-4"><span>Página {pagina} de {paginas}</span><div className="flex gap-2"><button className="btn-secondary" disabled={pagina<=1} onClick={()=>setPagina(p=>p-1)}><ChevronLeft/></button><button className="btn-secondary" disabled={pagina>=paginas} onClick={()=>setPagina(p=>p+1)}><ChevronRight/></button></div></footer></section>
 </div></main>{modal&&<div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/80 p-4"><div className="mx-auto max-w-4xl rounded-3xl border border-[var(--card-border)] bg-[var(--background)]"><header className="flex justify-between border-b border-[var(--card-border)] p-5"><h2 className="text-xl font-black">{modal==="crear"?"Nuevo empleado":modal==="editar"?"Editar empleado":"Ficha del empleado"}</h2><button onClick={()=>setModal(null)}><X/></button></header><div className="grid gap-4 p-5 md:grid-cols-2">
 {([['Empresa','empresaId','select'],['Código interno','codigo'],['Nombres','nombres'],['Apellidos','apellidos'],['DPI','dpi'],['NIT','nit'],['Afiliación IGSS','igss'],['Fecha ingreso','ingreso','date'],['Fecha retiro','retiro','date'],['Puesto','puesto'],['Departamento / área','departamento'],['Tipo contrato','contrato'],['Jornada','jornada'],['Salario base','salario','number'],['Bonificación','bonificacion','number'],['Observaciones','observaciones']] as Array<[string,keyof Form,string?]>).map(([label,key,type])=><label key={key}><span className="mb-1 block text-xs font-bold text-[var(--muted)]">{label}</span>{type==='select'?<select className="input-custom w-full" disabled={modal!=='crear'} value={form.empresaId} onChange={e=>setForm({...form,empresaId:e.target.value})}>{empresas.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select>:<input className="input-custom w-full" type={type||(["dpi","nit","igss"].includes(key)?"password":"text")} readOnly={modal==="ver"} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/>}</label>)}
 <label><span className="mb-1 block text-xs font-bold text-[var(--muted)]">Estado</span><select className="input-custom w-full" disabled={modal==="ver"} value={form.estado} onChange={e=>setForm({...form,estado:e.target.value})}>{ESTADOS.map(x=><option key={x}>{x}</option>)}</select></label><label><span className="mb-1 block text-xs font-bold text-[var(--muted)]">Moneda</span><select className="input-custom w-full" disabled={modal==="ver"} value={form.moneda} onChange={e=>setForm({...form,moneda:e.target.value})}><option>GTQ</option><option>USD</option></select></label>
 </div>{modal!=="ver"&&<footer className="flex justify-end border-t border-[var(--card-border)] p-5"><button className="btn-primary" disabled={guardando} onClick={()=>void guardar()}>{guardando?"Guardando…":"Guardar ficha"}</button></footer>}</div></div>}</div>;
}
function Aviso({error,children}:{error?:boolean;children:React.ReactNode}){return <div className={`rounded-xl border p-3 text-sm ${error?"border-red-500/30 bg-red-500/10 text-red-300":"border-emerald-500/30 bg-emerald-500/10 text-emerald-300"}`}>{children}</div>}
